//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphClient.GraphQueryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GraphQueryService.IGraphQueryService")]
    public interface IGraphQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphQueryService/GetShortestPath", ReplyAction="http://tempuri.org/IGraphQueryService/GetShortestPathResponse")]
        string[] GetShortestPath(string nodeIdFrom, string nodeIdTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphQueryService/GetShortestPath", ReplyAction="http://tempuri.org/IGraphQueryService/GetShortestPathResponse")]
        System.Threading.Tasks.Task<string[]> GetShortestPathAsync(string nodeIdFrom, string nodeIdTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphQueryServiceChannel : GraphClient.GraphQueryService.IGraphQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphQueryServiceClient : System.ServiceModel.ClientBase<GraphClient.GraphQueryService.IGraphQueryService>, GraphClient.GraphQueryService.IGraphQueryService {
        
        public GraphQueryServiceClient() {
        }
        
        public GraphQueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetShortestPath(string nodeIdFrom, string nodeIdTo) {
            return base.Channel.GetShortestPath(nodeIdFrom, nodeIdTo);
        }
        
        public System.Threading.Tasks.Task<string[]> GetShortestPathAsync(string nodeIdFrom, string nodeIdTo) {
            return base.Channel.GetShortestPathAsync(nodeIdFrom, nodeIdTo);
        }
    }
}
