//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphClient.GraphDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GraphDataService.IGraphDataService")]
    public interface IGraphDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphDataService/GetGraphNode", ReplyAction="http://tempuri.org/IGraphDataService/GetGraphNodeResponse")]
        GraphServices.DTO.GraphNode GetGraphNode(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphDataService/GetGraphNode", ReplyAction="http://tempuri.org/IGraphDataService/GetGraphNodeResponse")]
        System.Threading.Tasks.Task<GraphServices.DTO.GraphNode> GetGraphNodeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphDataService/GetAllGraphNodes", ReplyAction="http://tempuri.org/IGraphDataService/GetAllGraphNodesResponse")]
        GraphServices.DTO.GraphNode[] GetAllGraphNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphDataService/GetAllGraphNodes", ReplyAction="http://tempuri.org/IGraphDataService/GetAllGraphNodesResponse")]
        System.Threading.Tasks.Task<GraphServices.DTO.GraphNode[]> GetAllGraphNodesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphDataServiceChannel : GraphClient.GraphDataService.IGraphDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphDataServiceClient : System.ServiceModel.ClientBase<GraphClient.GraphDataService.IGraphDataService>, GraphClient.GraphDataService.IGraphDataService {
        
        public GraphDataServiceClient() {
        }
        
        public GraphDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GraphServices.DTO.GraphNode GetGraphNode(string id) {
            return base.Channel.GetGraphNode(id);
        }
        
        public System.Threading.Tasks.Task<GraphServices.DTO.GraphNode> GetGraphNodeAsync(string id) {
            return base.Channel.GetGraphNodeAsync(id);
        }
        
        public GraphServices.DTO.GraphNode[] GetAllGraphNodes() {
            return base.Channel.GetAllGraphNodes();
        }
        
        public System.Threading.Tasks.Task<GraphServices.DTO.GraphNode[]> GetAllGraphNodesAsync() {
            return base.Channel.GetAllGraphNodesAsync();
        }
    }
}
